config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pmduoet.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pmduoet/urls.py
from django.urls import path
from . import views


urlpatterns = [
        path('', views.index, name='index'),
]

pmduoet/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

# Create your models here.

class Municipio(models.Model):
    cve_mun = models.CharField(max_length=3, default=None, blank=True, null=True)
    nom_mun_corto = models.CharField(max_length=50, default=None, blank=True, null=True)
    nom_mun_largo = models.CharField(max_length=200, default=None, blank=True, null=True)
    img_mun = models.ImageField(upload_to='img/img_mun', default=None, blank=True, null=True)
    STATUS_AVANCE = (
            ('diagnostico', 'Diagnóstico'),
            ('elaboracion', 'Elaboración'),
            ('dictaminacion', 'Dictaminación'),
            ('revision', 'Revisión'),
            ('dictaminado', 'Dictaminado'),
            ('publicado', 'Publicado'),
            ('pendiente', 'Pendiente'),
            )
    status = models.TextField(
        max_length=20,
        choices=STATUS_AVANCE,
        blank=True,
        help_text='Status del avance',
        )

    @property
    def img_mun_url(self):
        if self.img_mun and hasattr(self.img_mun, 'url'):
            return self.img_mun.url

    def __str__(self):
        return f"{self.cve_mun} {self.nom_mun_corto}"

    class Meta:
        ordering = ['cve_mun']


class Documento(models.Model):
    municipio = models.ForeignKey(Municipio, on_delete=models.PROTECT)
    etiqueta = models.TextField(default=None, blank=True, null=True)
    url = models.TextField(default=None, blank=True, null=True)
    archivo = models.FileField(upload_to='docs', default=None, blank=True, null=True)
    posicion = models.IntegerField(default=None, blank=True, null=True)

    def __str__(self):
        return f"{self.municipio.cve_mun} {self.municipio.nom_mun_corto} - {self.posicion} - {self.etiqueta}"

    class Meta:
        ordering = ['municipio', 'posicion']

class Avance(models.Model):
    municipio = models.ForeignKey(Municipio, on_delete=models.PROTECT)
    nombre = models.TextField(max_length=200, default=None, blank=True, null=True)
    TIPO_AVANCE = (
            ('parcial', 'Programa parcial'),
            ('municipal', 'Programa municipal'),
            )
    tipo = models.TextField(
        max_length=20,
        choices=TIPO_AVANCE,
        blank=True,
        default='municipal',
        help_text='Tipo de avance',
        )
    STATUS_AVANCE = (
            ('diagnostico', 'Diagnóstico'),
            ('elaboracion', 'Elaboración'),
            ('dictaminacion', 'Dictaminación'),
            ('revision', 'Revisión'),
            ('dictaminado', 'Dictaminado'),
            ('publicado', 'Publicado'),
            ('pendiente', 'Pendiente'),
            )
    status = models.TextField(
        max_length=20,
        choices=STATUS_AVANCE,
        blank=True,
        default='diagnostico',
        help_text='Status del avance',
        )
    dictaminacion = models.DateField(default=None, null=True, blank=True)
    publicacion = models.DateField(null=True, blank=True)
    comentarios = models.TextField(max_length=200, default=None, blank=True, null=True)
    actualizado = models.DateTimeField(auto_now=True)

    def __str__(self):
        """String for representing the Avance object (in Admin site etc.)"""
        return f'{self.municipio.nom_mun_corto} ({self.tipo}) - {self.status}'

pmduoet/views.py
from django.shortcuts import render
from django.views import generic
from .models import Municipio, Avance
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def index(request):
    """View function for home page of site."""

    # generar lista de Municipios
    municipio_list = Municipio.objects.all()

    # "municipio" mapa
    mapa = Municipio.objects.filter(cve_mun='200').first()

    # Ultima actualizacion
    ultima_actualizacion = Avance.objects.latest('actualizado').actualizado

    context = {
            'municipio_list': municipio_list,
            'mapa': mapa,
            'ultima_actualizacion': ultima_actualizacion,
            }

    return render(request, 'index.html', context=context)

pmduoet/templates/base.html
<!DOCTYPE html>
<html lang="es" data-bs-theme="auto">
    <head>
        {% load static %}
        <script src="{% static 'js/color-modes.js' %}"></script>
        <link rel="icon" href="{% static 'img/favicon.png' %}" sizes="16x16" type="image/png" />
        <link rel="icon" href="{% static 'img/favicon.png' %}" sizes="32x32" type="image/png" />

        {% block title %}
            <title>PMDUOET</title>
        {% endblock %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

        <!-- Add additional CSS in static file -->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    <!-- Favicons -->
<meta name="theme-color" content="#712cf9">


    </head>

    <body>
        <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
            <symbol id="check2" viewBox="0 0 16 16">
                <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
            </symbol>
            <symbol id="circle-half" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
            </symbol>
            <symbol id="moon-stars-fill" viewBox="0 0 16 16">
                <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
                <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
            </symbol>
            <symbol id="sun-fill" viewBox="0 0 16 16">
                <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
            </symbol>
        </svg>

        <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
            <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
                id="bd-theme"
                type="button"
                aria-expanded="false"
                data-bs-toggle="dropdown"
                aria-label="Toggle theme (auto)">
                <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
                <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
                <li>
                <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
                    <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
                    Light
                    <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
                </button>
                </li>
                <li>
                <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
                    <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
                    Dark
                    <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
                </button>
                </li>
                <li>
                <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
                    <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
                    Auto
                    <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
                </button>
                </li>
            </ul>
        </div>

        <header data-bs-theme="dark">
            <div class="navbar shadow-sm">
                <div class="container">
                    <div class="col-sm-12 text-center">
                        <div class="row justify-content-between">
                            <div class="col-sm-5 me-auto">
                                <div class="row">
                                    <div class="col">
                                        <img class="logo" src="{% static 'img/gto_iplaneg.png' %}">
                                    </div>
                                    <div class="col mt-3">
                                        <h5>Revisión PMDUOETs</h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-auto mt-3">
                                {% if user.is_authenticated %}
                                    <ul class="nav">
                                        <li>{{ user.first_name }} {{user.last_name}}</li>
                                        {% if user.is_staff %}
                                            <li>&nbsp; | &nbsp;<a href="{% url 'admin:index' %}">Administración</a>&nbsp; | &nbsp;</li>
                                        {% endif %}
                                        <li class="mt-0">
                                            <form id="logout-form" method="post" action="{% url 'logout' %}">
                                                {% csrf_token %}
                                                <button type="submit" class="btn btn-link pt-0">Salir</button>
                                            </form>
                                        </li>
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <main>
            {% block content %}
            {% endblock %}
        </main>
    </body>
</html>

pmduoet/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <section class="py-5 text-center container">
        <div class="row py-lg-3">
            <div class="col-lg-10 col-md-10 mx-auto">
                <h1 class="fw-light">Documentación PMDUOETs</h1>
                <p class="lead text-body-secondary">Repositorio de documentación de los proyectos de programas municipales para revisión y análisis de la congruencia y vinculación respecto a la planeación nacional y estatal, a realizarse por las dependencias y entidades de la administración pública estatal conforme a las materias de su competencia con fundamento en el artículo 58 fracción VIII inciso b del Código Territorial para el Estado y los Municipios de
                    Guanajuato y el artículo 9 de los Lineamientos Técnicos que deberán atender los Municipios en la presentación de los proyectos de Programas Municipales de Desarrollo Urbano y Ordenamiento Ecológico Territorial para su dictamen y validación.</p>
            </div>
        </div>
    </section>


    <div class="col-sm-12">
        <ul class="nav nav-tabs mb-3 justify-content-center" id="pills-tab" role="tablist">
            <li class="nav-item" role="presentation">
            <a href="#" class="nav-link fs-4 active" id="pills-30years-tab" data-bs-toggle="pill" data-bs-target="#pills-30years" role="tab" aria-controls="pills-30years" aria-selected="true">Avances</a>
            </li>
            <li class="nav-item" role="presentation">
            <a href="#" class="nav-link fs-4" id="pills-queped-tab" data-bs-toggle="pill" data-bs-target="#pills-queped" role="tab" aria-controls="pills-queped" aria-selected="false">Documentos</a>
            </li>
        </ul>
    </div>

    <div class="col-sm-12">
        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-30years" role="tabpanel" aria-labelledby="pills-30years-tab" tabindex="0">
                <p class="text-end me-5">Ultima actualización: {{ ultima_actualizacion }}</p>
                {% if municipio_list %}
                    <div class="col-sm-10 offset-1">
                        <h4 class="text-center">Programas municipales</h4>
                        <table class="table">
                            <thead class="table-dark">
                                <tr>
                                    <th scope="col">Municipio</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Dictaminación</th>
                                    <th scope="col">Publicación</th>
                                    <th scope="col">Comentarios</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for municipio in municipio_list %}
                                    {% if municipio.avance_set.all %}
                                        {% for avance in municipio.avance_set.all %}
                                            {% if avance.tipo == 'municipal' %}
                                            <tr>
                                                <td>{{ avance.municipio.nom_mun_corto }}</td>
                                                <td>{{ avance.get_status_display }}</td>
                                                <td>{{ avance.dictaminacion|default_if_none:'' }}</td>
                                                <td>{{ avance.publicacion|default_if_none:'' }}</td>
                                                <td>{{ avance.comentarios }}</td>
                                            </tr>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <div class="col-sm-10 offset-1 mb-5">
                        <h4 class="text-center">Programas parciales</h4>
                        <table class="table">
                            <thead class="table-dark">
                                <tr>
                                    <th scope="col">Municipio</th>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Dictaminación</th>
                                    <th scope="col">Publicación</th>
                                    <th scope="col">Comentarios</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for municipio in municipio_list %}
                                    {% if municipio.avance_set.all %}
                                        {% for avance in municipio.avance_set.all %}
                                            {% if avance.tipo == 'parcial' %}
                                            <tr>
                                                <td>{{ avance.municipio.nom_mun_corto }}</td>
                                                <td>{{ avance.nombre }}</td>
                                                <td>{{ avance.get_status_display }}</td>
                                                <td>{{ avance.dictaminacion|default_if_none:'' }}</td>
                                                <td>{{ avance.publicacion|default_if_none:'' }}</td>
                                                <td>{{ avance.comentarios }}</td>
                                            </tr>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <div class="col-sm-10 offset-1 mb-5 text-center">
                        {% if mapa %}
                            <img class="img-fluid" src="{{ mapa.img_mun_url }}">
                        {% endif %}
                    </div>
                {% else %}
                    <p>No hay avances registrados</p>
                {% endif %}

            </div>

            <div class="tab-pane fade" id="pills-queped" role="tabpanel" aria-labelledby="pills-queped-tab" tabindex="0">
                {% if municipio_list %}
                    <div class="album py-5 bg-body-tertiary">
                        <div class="container">
                            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                                {% for municipio in municipio_list %}
                                    {% if municipio.documento_set.all %}
                                        <div class="col">
                                            <div class="card shadow-sm">
                                                {% if municipio.img_mun %}
                                                    <img src="{{ municipio.img_mun_url }}">
                                                {% else %}
                                                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ municipio.nom_mun_corto }}</text></svg>
                                                {% endif %}

                                                <div class="card-body">
                                                    <p class="card-text text-center">
                                                        {{ municipio.nom_mun_largo }} <br />
                                                        <small class="text-secondary">{{ municipio.get_status_display }}</small>
                                                    </p>
                                                    {% for documento in municipio.documento_set.all %}
                                                        {% if documento.archivo %}
                                                            <a href="{% get_media_prefix %}{{ documento.archivo }}" class="btn btn-sm btn-outline-secondary mb-1" target="_blank">{{ documento.etiqueta }}</a>
                                                        {% endif %}
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% else %}
                    <p>No hay municipios registrados</p>
                {% endif %}
            </div>
        </div>
    </div>


{% endblock %}

pmduoet/templates/pmduoet/municipio_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <section class="py-5 text-center container">
        <div class="row py-lg-3">
            <div class="col-lg-10 col-md-10 mx-auto">
                <h1 class="fw-light">Documentación PMDUOETs</h1>
                <p class="lead text-body-secondary">Repositorio de documentación de los proyectos de programas municipales para revisión y análisis de la congruencia y vinculación respecto a la planeación nacional y estatal, a realizarse por las dependencias y entidades de la administración pública estatal conforme a las materias de su competencia con fundamento en el artículo 58 fracción VIII inciso b del Código Territorial para el Estado y los Municipios de
                    Guanajuato y el artículo 9 de los Lineamientos Técnicos que deberán atender los Municipios en la presentación de los proyectos de Programas Municipales de Desarrollo Urbano y Ordenamiento Ecológico Territorial para su dictamen y validación.</p>
            </div>
        </div>
    </section>

    {% if municipio_list %}
        <div class="album py-5 bg-body-tertiary">
            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for municipio in municipio_list %}
                        {% if municipio.documento_set.all %}
                            <div class="col">
                                <div class="card shadow-sm">
                                    {% if municipio.img_mun %}
                                        <img src="{{ municipio.img_mun_url }}">
                                    {% else %}
                                        <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ municipio.nom_mun_corto }}</text></svg>
                                    {% endif %}

                                    <div class="card-body">
                                        <p class="card-text text-center">{{ municipio.nom_mun_largo }}</p>
                                        {% for documento in municipio.documento_set.all %}
                                            {% if documento.archivo %}
                                                <a href="{% get_media_prefix %}{{ documento.archivo }}" class="btn btn-sm btn-outline-secondary mb-1" target="_blank">{{ documento.etiqueta }}</a>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        <p>No hay municipios registrados</p>
    {% endif %}
{% endblock %}